### ISSUE TITLE
Icons of Method and Function are Different

### ISSUE THREAD

**Issue by yttriumz** [antfu/vscode-icons-carbon#12]
### Describe the bug

The icon of a method is different from that of a function (in a Python file), as shown below. Is this an issue or a feature?

![image](https://user-images.githubusercontent.com/43232804/194736146-35dae4c2-f1ef-4cc4-bbe9-5e8e026dd123.png)

![image](https://user-images.githubusercontent.com/43232804/194736163-50119dec-4684-4fd9-ae06-d0362611d304.png)

### Reproduction

Apply our product icon theme

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
    Memory: 15.20 GB / 31.71 GB
  Binaries:
    Node: 16.17.0 - C:\Program_Files\nodejs\node.EXE
    npm: 8.15.0 - C:\Program_Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.37)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
I prefer to consider it a feature

**Comment by yttriumz** [comment]
> I prefer to consider it a feature

The feature itself is excellent :) 

Here are some suggestions:

- Change the icon of methods (the purple box) to [function icon](https://carbon-elements.netlify.app/icons/examples/preview/#Function32) (the current icon for functions). Because it has a circle on the background, making it more like a combination of "object" and "function", which is "method".
- Change the icon of functions to [function-math icon](https://carbon-elements.netlify.app/icons/examples/preview/#FunctionMath32). Because it looks like a "pure function".

**Comment by antfu** [comment]
Sounds good, PR welcome

**Comment by yttriumz** [comment]
> Sounds good, PR welcome

I would like to make a PR. But seems this project's structure is a bit different from other icon themes I saw.

For example, [fluent icon](https://github.com/miguelsolorio/vscode-fluent-icons) and [material icon](https://github.com/PKief/vscode-material-product-icons) all have a `theme` folder containing the files controlling the theme. But I didn't find it here.

It's a bit awkward, but could you explain a bit about how to contribute to the project :)

**Comment by antfu** [comment]
You just need to update the icon ids of https://github.com/antfu/vscode-icons-carbon/blob/main/scripts/sets.ts

**Comment by Pustur** [comment]
Just as a heads up, now some css properties show up as functions:

<img width="203" alt="Screenshot 2022-10-10 at 11 58 37" src="https://user-images.githubusercontent.com/13663338/194841368-03cf1ba6-e63a-4449-bcf5-aaffd3ad62f4.png">

**Comment by yttriumz** [comment]
> Just as a heads up, now some css properties show up as functions:

Sorry I'm not familiar with front-end things :( 

But could you try reverting the icon theme to the previous version and check how they show up? If they show up as "an f with a circle" with the previous version, I think #13 is OK. Otherwise, it's problematic.

**Comment by Pustur** [comment]
Yes they show up like this in the previous version. So it's always been a bit weird 😅  
For some reason I thought they were cubes previously.

<img width="190" alt="Screenshot 2022-10-10 at 12 14 13" src="https://user-images.githubusercontent.com/13663338/194844095-920cf6f6-d5aa-48f4-a987-d929d44188d6.png">

**Comment by yttriumz** [comment]
@Pustur I guess there might be some problems with VSCode's JS/TS code completions function 🤔? 

In the following screenshot, all the **properties** (symbol-property) in code completion are labeled with a cube, which is configured to represent **field** (symbol-field). But in the outline view, those properties are properly labeled.

![image](https://user-images.githubusercontent.com/43232804/195329745-6f5ff8eb-7242-4c82-8832-812994376d85.png)
