### ISSUE TITLE
Font name

### ISSUE THREAD

**Issue by prajapati-parth** [antfu/vscode-icons-carbon#7]
<img width="878" alt="preview" src="https://user-images.githubusercontent.com/17194534/117261277-9b978980-ae6d-11eb-95c2-733a9ef2d998.png">

What are the fonts used in the editor?

**Comment by antfu** [comment]
Input Mono

**Comment by prajapati-parth** [comment]
Thanks. But some of the letters are not matching with the screenshot from your readme. Check the letter `a` and `g`.
<img width="680" alt="Screenshot 2021-05-06 at 2 50 12 PM" src="https://user-images.githubusercontent.com/17194534/117274169-70fffd80-ae7a-11eb-84f4-1f2b9676cc86.png">

**Comment by prajapati-parth** [comment]
Found a customisation option in font down that will update a and g. Thank you again.

**Comment by antfu** [comment]
Input Mono is customizable
