### ISSUE TITLE
Publish to open-vsx

### ISSUE THREAD

**Issue by kytta** [antfu/vscode-icons-carbon#9]
A popular FLOSS-only fork of VSCode, [VSCodium](https://github.com/VSCodium/vscodium), uses a different extension store for legal reasons: [Open VSX](https://open-vsx.org/) instead of the Visual Studio Marketplace. It would be helpful, if you would publish this extension there as well 🙌 

The rather simple process is described here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by antfu** [comment]
https://open-vsx.org/extension/antfu/icons-carbon
